import { Router } from 'express'
import { isValidObjectId } from 'mongoose'
import { z } from 'zod'
import { Appointment, appointmentStatuses } from './model.js'
import { Customer, Service, Staff, Availability } from '../domains/models.js'
import { requireAuthentication, requirePermissions } from '../middleware/auth.js'
import { HttpError } from '../shared/errors.js'
const id=z.string().regex(/^[a-f\d]{24}$/i), time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), date=z.string().date()
const body=z.object({customerId:id,serviceId:id,staffId:id,date,startTime:time,status:z.enum(appointmentStatuses).optional()})
const editable=body.partial().omit({status:true}).extend({status:z.enum(appointmentStatuses).optional()})
const minutes=(v:string)=>{const[a,b]=v.split(':').map(Number);return a*60+b};const fmt=(v:number)=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`
async function validate(input:any,exclude?:string){const [customer,service,staff]=await Promise.all([Customer.findById(input.customerId),Service.findById(input.serviceId),Staff.findById(input.staffId)]);if(!customer||customer.status!=='active'||!service||service.status!=='active'||!staff||staff.status!=='active')throw new HttpError(400,'VALIDATION_ERROR','Referenced record is unavailable.');const end=fmt(minutes(input.startTime)+service.durationMinutes);if(minutes(end)>1440)throw new HttpError(400,'VALIDATION_ERROR','Appointment exceeds the day.');const availability=await Availability.findOne({staffId:input.staffId,date:input.date,status:'active'});if(!availability||minutes(input.startTime)<minutes(availability.startTime)||minutes(end)>minutes(availability.endTime))throw new HttpError(400,'VALIDATION_ERROR','Staff is unavailable at this time.');const conflicts=await Appointment.find({staffId:input.staffId,date:input.date,status:{$nin:['cancelled','no_show']},_id:{$ne:exclude}});if(conflicts.some((x:any)=>minutes(input.startTime)<minutes(x.endTime)&&minutes(end)>minutes(x.startTime)))throw new HttpError(400,'VALIDATION_ERROR','Staff has a conflicting appointment.');return end}
export const appointmentRouter=Router();appointmentRouter.use(requireAuthentication)
appointmentRouter.post('/',requirePermissions('appointments.manage'),async(r,s,n)=>{try{const x=body.parse(r.body);const end=await validate(x);s.status(201).json({data:await Appointment.create({...x,endTime:end})})}catch(e){n(e)}})
appointmentRouter.get('/',requirePermissions('appointments.manage'),async(r,s,n)=>{try{const q=z.object({date:date.optional(),startDate:date.optional(),endDate:date.optional(),staffId:id.optional(),customerId:id.optional(),serviceId:id.optional(),status:z.enum(appointmentStatuses).optional(),page:z.coerce.number().min(1).default(1),limit:z.coerce.number().min(1).max(100).default(20)}).parse(r.query);const f:any={};for(const k of ['staffId','customerId','serviceId','status'] as const)if(q[k])f[k]=q[k];if(q.date)f.date=q.date;else if(q.startDate||q.endDate)f.date={$gte:q.startDate,$lte:q.endDate};const[data,total]=await Promise.all([Appointment.find(f).sort({date:1,startTime:1}).skip((q.page-1)*q.limit).limit(q.limit),Appointment.countDocuments(f)]);s.json({data,pagination:{page:q.page,limit:q.limit,total}})}catch(e){n(e)}})
appointmentRouter.get('/queue/today',requirePermissions('queue.manage'),async(_r,s,n)=>{try{s.json({data:await Appointment.find({date:new Date().toISOString().slice(0,10),status:{$in:['scheduled','arrived','in_progress']}}).sort({startTime:1})})}catch(e){n(e)}})
appointmentRouter.get('/:id',requirePermissions('appointments.manage'),async(r,s,n)=>{try{if(!isValidObjectId(r.params.id))throw new HttpError(400,'VALIDATION_ERROR','Invalid identifier.');const d=await Appointment.findById(r.params.id);if(!d)throw new HttpError(404,'NOT_FOUND','Appointment not found.');s.json({data:d})}catch(e){n(e)}})
appointmentRouter.patch('/:id',requirePermissions('appointments.manage'),async(r,s,n)=>{try{if(!isValidObjectId(r.params.id))throw new HttpError(400,'VALIDATION_ERROR','Invalid identifier.');const current:any=await Appointment.findById(r.params.id);if(!current)throw new HttpError(404,'NOT_FOUND','Appointment not found.');if(['completed','cancelled','no_show'].includes(current.status))throw new HttpError(400,'VALIDATION_ERROR','This appointment cannot be changed.');const x=editable.parse(r.body);const next={...current.toObject(),...x};const end=await validate(next,String(current._id));const d=await Appointment.findByIdAndUpdate(r.params.id,{...x,endTime:end},{new:true});s.json({data:d})}catch(e){n(e)}})
