import { Schema, model } from 'mongoose'

const status = { type: String, enum: ['active', 'inactive'], default: 'active', required: true } as const
export const Customer = model('Customer', new Schema({ displayName: { type: String, required: true, trim: true }, email: { type: String, trim: true, lowercase: true, sparse: true, unique: true }, phone: { type: String, trim: true }, status, notes: { type: String, trim: true } }, { timestamps: true }))
export const ServiceCategory = model('ServiceCategory', new Schema({ name: { type: String, required: true, trim: true, unique: true }, status }, { timestamps: true }))
export const Service = model('Service', new Schema({ name: { type: String, required: true, trim: true }, categoryId: { type: Schema.Types.ObjectId, ref: 'ServiceCategory', required: true }, price: { type: Number, required: true, min: 0 }, durationMinutes: { type: Number, required: true, min: 1 }, status }, { timestamps: true }))
export const ServicePackage = model('ServicePackage', new Schema({ name: { type: String, required: true, trim: true }, serviceIds: [{ type: Schema.Types.ObjectId, ref: 'Service' }], status }, { timestamps: true }))
export const Staff = model('Staff', new Schema({ displayName: { type: String, required: true, trim: true }, designation: { type: String, trim: true }, email: { type: String, trim: true, lowercase: true }, phone: { type: String, trim: true }, status }, { timestamps: true }))
export const Availability = model('Availability', new Schema({ staffId: { type: Schema.Types.ObjectId, ref: 'Staff', required: true }, date: { type: String, required: true }, startTime: { type: String, required: true }, endTime: { type: String, required: true }, status }, { timestamps: true }))
export const Attendance = model('Attendance', new Schema({ staffId: { type: Schema.Types.ObjectId, ref: 'Staff', required: true }, date: { type: String, required: true }, status: { type: String, enum: ['present', 'absent'], required: true }, checkIn: String, checkOut: String }, { timestamps: true }))
export const Leave = model('Leave', new Schema({ staffId: { type: Schema.Types.ObjectId, ref: 'Staff', required: true }, startDate: { type: String, required: true }, endDate: { type: String, required: true }, status: { type: String, enum: ['pending', 'approved', 'rejected'], default: 'pending' }, reason: { type: String, trim: true } }, { timestamps: true }))
