import { useState, type FormEvent } from 'react'
import { useAuth } from '../../features/auth/AuthProvider'
import { ApiError } from '../api/ApiError'
import { apiRequest } from '../api/client'

export function ApiMutationPanel({ title, path, fields, method = 'POST', onSuccess }: { title: string; path: string; fields: readonly { name: string; label: string; required?: boolean; type?: string; route?: boolean }[]; method?: 'POST' | 'PATCH'; onSuccess?: () => void }) {
  const { session } = useAuth(); const [error, setError] = useState<string>(); const [submitting, setSubmitting] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!session) return; const form = new FormData(event.currentTarget); const body: Record<string, unknown> = Object.fromEntries([...form.entries()].filter(([, value]) => String(value).trim() !== '')); for (const field of fields) if (field.type === 'number' && body[field.name] !== undefined) body[field.name] = Number(body[field.name]); const resolvedPath = fields.filter((field) => field.route).reduce((value, field) => value.replace(`:${field.name}`, encodeURIComponent(String(body[field.name] || ''))), path); fields.filter((field) => field.route).forEach((field) => delete body[field.name]); setSubmitting(true); setError(undefined); try { await apiRequest({ path: resolvedPath, method, token: session.accessToken, body }); event.currentTarget.reset(); onSuccess?.() } catch (cause) { setError(cause instanceof ApiError && cause.status === 400 ? 'The API rejected this request. Review the required IDs and values.' : 'Unable to submit this request.') } finally { setSubmitting(false) } }
  return <section className="contract-section"><h2>{title}</h2><form onSubmit={submit}><div className="form-grid">{fields.map((field) => <label key={field.name}>{field.label}<input name={field.name} required={field.required} type={field.type || 'text'} disabled={submitting} /></label>)}</div>{error && <p className="form-error">{error}</p>}<button className="button" disabled={submitting}>{submitting ? 'Submitting…' : 'Submit'}</button></form></section>
}
